- name: Remove malicious files
  hosts: win
  gather_facts: true

  tasks:
    - name: Delete file
      ansible.windows.win_file:
        path: "{{ item }}"
        state: absent
      loop: "{{ file_path }}"

    - name: Create log file if absent
      ansible.windows.win_file:
        path: C:\Users\Administrator\Desktop\Log\malware_cleanup.log
        state: touch

    - name: Log deletion
      ansible.windows.win_shell: echo "{{ ansible_date_time.iso8601 }} - {{ item }} - deleted" >> C:\Users\Administrator\Desktop\Log\malware_cleanup.log
      loop: "{{ file_path }}"
