---
- name: Listen for webhook events
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: test:test@aap.example.org
        port: 5000

  rules:
    - name: Handle malicious file
      condition: event.payload.message == "malicious files"
      action:
        run_job_template:
          name: deletefiles
          extra_vars:
            file_path: "{{ event.payload.paths }}"

    - name: Regular Ping
      condition: event.payload.message == "check os"
      action:
        run_job_template:
          name: check
