---
- name: Listen for webhook events
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 192.168.201.129
        port: 5000

  rules:
    - name: Run job if event received
      condition: event.payload.message is defined
      action:
        run_playbook:
          name: playbook.yaml
